# vib-MC server properties
allow-end=true
allow-flight=false
allow-nether=true
autosave-interval-ticks=6000
debug=false
difficulty=easy
generate-structures=true
level-name=world
level-type=default
max-build-height=320
max-players=20
max-tick-time=60000
motd=A vib-MC Server
online-mode=false
pvp=true
proxy-mode=none
proxy-trusted-address=127.0.0.1
resource-pack=
resource-pack-sha1=
seed=
server-ip=0.0.0.0
server-port=25565
shutdown-message=Server closed
simulation-distance=8
spawn-animals=true
spawn-monsters=true
view-distance=4
